### ISSUE TITLE
Updating to 0.24.1 but cannot find the image 1.22.1

### ISSUE THREAD

**Issue by peterabarr** [aws/aws-node-termination-handler#1048]
**Describe the bug**
Unable to consume the latest `1.22.1` image via the helm chart `0.24.1` and receiving the message **"failed to pull and unpack image "public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.22.1": no match for platform in manifest: not found".**

I tried pulling the chart locally using:
```bash
helm pull oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler --version 0.24.1
```

And in the `Chart.yaml` file it looks correct showing:
```yaml
appVersion: 1.22.1
```

**Steps to reproduce**
Applying the `0.24.1` chart update

**Expected outcome**
I expected the node termination handler pod would be running `1.22.1`.

**Application Logs**
The log output when experiencing the issue.

**Environment**

* NTH App Version: 1.22
* NTH Mode (IMDS/Queue processor): 
* OS/Arch: Linux
* Kubernetes version: 1.29
* Installation method: Terraform

**Comment by LikithaVemulapalli** [comment]
Hello @peterabarr, we had an issue earlier with the release and reverted it. We fixed the issue and did release again, I'm assuming you tried pulling the image during this period. We can see all the linux, windows binaries and helm chart hosted in their respective ECR public repository successfully. There shouldn't be any issues now, could you please retry and confirm. Thanks :)
https://gallery.ecr.aws/aws-ec2/aws-node-termination-handler
https://gallery.ecr.aws/aws-ec2/helm/aws-node-termination-handler

**Comment by maxsxu** [comment]
Hi @LikithaVemulapalli , still unable to pull `public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.22.1`, see below errors:

```
[root@ip-10-60-10-140 /]# ctr i pull public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.22.1
public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.22.1:                   resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:963ea4fc49dceb13d5808ca37a24fbab32b793e7508b22e2bdf876177ed70752: done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 0.2 s                                                                 total:   0.0 B (0.0 B/s)
unpacking linux/amd64 sha256:963ea4fc49dceb13d5808ca37a24fbab32b793e7508b22e2bdf876177ed70752...
ctr: no match for platform in manifest sha256:963ea4fc49dceb13d5808ca37a24fbab32b793e7508b22e2bdf876177ed70752: not found
```

But able to pull `public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.22.1-linux-amd64`

```
[root@ip-10-60-10-140 /]# ctr i pull public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.22.1-linux-amd64
public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.22.1-linux-amd64:          resolved       |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:f3bd5bf94b739bc12e78f7b1413c1a57d6f28c76e93bb24026b3a1f890e79893: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:29119a36903399e264a895854086d2ea7ba31222a74ab2b40efb7013bcb34799:    done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:1b9649cca03ce12b3194a279084c93b447edff4e84e3a5fb232d1130370b6506:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:00f4f8ffb200c80ce97f3a3d3e369bf1e133d417d44dc5c4a3c7f4727eb2f55f:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:cc963b6a58593f5fff8d7198adaed419984a2c4ab841c03a466dd58b68746fe9:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 1.8 s                                                                    total:  16.2 M (9.0 MiB/s)
unpacking linux/amd64 sha256:f3bd5bf94b739bc12e78f7b1413c1a57d6f28c76e93bb24026b3a1f890e79893...
done: 320.115494ms
```

**Comment by steveshidev** [comment]
The docker image manifest should be fixed now. Resolving.

**Comment by maxsxu** [comment]
Confirmed this issue has been fixed.

**Comment by peterabarr** [comment]
Yeah working on my end now, will close this issue. Thanks!
